import * as THREE from '../vendor/three.module.js';
import { generateMap } from './core/generator.js';
import { DEFAULT_TUNING, simulateStep } from './core/simulator.js';
import { totalLength } from './core/schema.js';

const $=id=>document.getElementById(id),canvas=$('game'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'}),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(61,innerWidth/innerHeight,.1,900),world=new THREE.Group(),keys=new Set(),touch={left:0,right:0,accelerate:0,brake:0};
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.55;scene.add(world,new THREE.HemisphereLight(0xc6ffff,0x102026,3.2));scene.fog=new THREE.FogExp2(0x071116,.0027);const sun=new THREE.DirectionalLight(0xffedce,4.5);sun.position.set(-8,14,-6);scene.add(sun);
const colors={boost:0x60ef9e,slow:0xf1b550,obstacle:0xff575f,jump:0x62b7ff,'slow-wall':0xd57bcf,energy:0xffe75f,'item-box':0x55ddf2,oil:0x705588,'moving-gate':0xff8568};
const VEHICLES={comet:{name:'彗星 MK-I',trait:'均衡响应 · 推荐新车手',color:0x65e29f,accent:0xeafff3,maxSpeed:42,steer:1,stability:1},razor:{name:'风刃 GT',trait:'极速推进 · 精准压弯',color:0xff5f55,accent:0xffdd64,maxSpeed:47,steer:.88,stability:.78},trail:{name:'岩虎 R',trait:'强力抓地 · 宽容稳定',color:0xffc44f,accent:0x65e29f,maxSpeed:38,steer:.94,stability:1.35},pulse:{name:'脉冲 X',trait:'灵敏漂移 · 快速充能',color:0x68b8ff,accent:0xe883ff,maxSpeed:44,steer:1.18,stability:.86}};
let map,state,samples,phase='garage',seed=4517,countdown=0,last=performance.now(),maxSpeed=0,collisions=0,track,features,player,decor,selectedVehicle=localStorage.getItem('core-luge.vehicle')||'comet';
function setPhase(next){phase=next;for(const id of['garage','menu','countdown','paused','results'])$(id).hidden=next!==id;const racing=['countdown','race'].includes(next);$('race-hud').hidden=!racing;$('energy').hidden=!racing;$('pause').hidden=next!=='race';$('touch-controls').hidden=next!=='race'}
function dispose(group){if(!group)return;group.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose?.()});group.removeFromParent()}
function reset(){state={speed:4,lateral:0,distance:0,elapsed:0,penalties:0,hit:new Set(),energy:0,combo:0,driftCharge:0,boostTimer:0,shieldTimer:0,event:'后仰加速'};maxSpeed=collisions=0}
function build(nextSeed=seed){seed=nextSeed>>>0;map=generateMap({seed,duration:105,difficulty:Number($('difficulty').value),complexity:.72,shape:'mixed',environment:['reef','alpine','neon-city','volcanic','aurora'][seed%5]});reset();[track,features,player,decor].forEach(dispose);samples=sampleCourse(map);track=makeTrack();features=makeFeatures();player=makePlayer();decor=makeDecor();world.add(track,features,player,decor);theme(map.environment);place(true)}
function sampleCourse(course){const out=[];let x=0,y=0,z=0,heading=0,distance=0;for(const segment of course.segments){const steps=Math.max(4,Math.ceil(segment.len/4));for(let i=0;i<steps;i++){heading+=(segment.yaw||0)*Math.PI/180/steps;const slope=(segment.drop||0)*Math.PI/180;x+=Math.sin(heading)*4;z+=Math.cos(heading)*4;y-=Math.sin(slope)*4;out.push({x,y,z,heading,distance,segment});distance+=4}}return out}
function at(distance){const i=Math.max(0,Math.min(samples.length-2,Math.floor(distance/4))),a=samples[i],b=samples[i+1],t=(distance-a.distance)/Math.max(1,b.distance-a.distance);return{x:THREE.MathUtils.lerp(a.x,b.x,t),y:THREE.MathUtils.lerp(a.y,b.y,t),z:THREE.MathUtils.lerp(a.z,b.z,t),heading:THREE.MathUtils.lerp(a.heading,b.heading,t),segment:a.segment}}
function makeTrack(){const geo=new THREE.BufferGeometry(),v=[],c=[],ind=[],width=11;for(let i=0;i<samples.length;i++){const p=samples[i],rx=Math.cos(p.heading),rz=-Math.sin(p.heading);for(let lane=0;lane<=12;lane++){const u=lane/12,across=(u-.5)*width,bank=Math.sin(u*Math.PI)*1.15,edge=Math.min(u,1-u),glow=edge<.09?1:.2;v.push(p.x+rx*across,p.y-bank,p.z+rz*across);c.push(.12+glow*.12,.25+glow*.52,.28+glow*.55);if(i<samples.length-1&&lane<12){const a=i*13+lane,b=a+13;ind.push(a,b,a+1,a+1,b,b+1)}}}geo.setAttribute('position',new THREE.Float32BufferAttribute(v,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(c,3));geo.setIndex(ind);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.63,metalness:.25,side:THREE.DoubleSide}));const lineMat=new THREE.LineBasicMaterial({color:0x78f9e4});for(const side of[-1,1]){const points=samples.filter((_,i)=>i%2===0).map(p=>new THREE.Vector3(p.x+Math.cos(p.heading)*width*.5*side,p.y+.08,p.z-Math.sin(p.heading)*width*.5*side));mesh.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),lineMat))}return mesh}
function distanceOf(feature){let d=0;for(const segment of map.segments){if(segment.id===feature.segmentId)return d+feature.offset;d+=segment.len}return 0}
function makeFeatures(){const group=new THREE.Group();for(const feature of map.features){const frame=at(distanceOf(feature)),mat=new THREE.MeshStandardMaterial({color:colors[feature.type]||0xffffff,emissive:colors[feature.type]||0xffffff,emissiveIntensity:.7,roughness:.3});let mesh;if(feature.type==='energy'){mesh=new THREE.Mesh(new THREE.TorusGeometry(.7,.16,10,24),mat);mesh.position.y=1.2}else if(feature.type==='item-box'){mesh=new THREE.Mesh(new THREE.BoxGeometry(1.25,1.25,1.25),mat);mesh.rotation.y=Math.PI/4;mesh.position.y=1}else if(['obstacle','moving-gate'].includes(feature.type)){mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(1.6,feature.width*4),1.5,1),mat);mesh.position.y=.75}else{mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(1.4,feature.width*5),.12,Math.max(2,feature.length)),mat);mesh.position.y=.08}mesh.position.add(new THREE.Vector3(frame.x,frame.y,frame.z)).addScaledVector(new THREE.Vector3(Math.cos(frame.heading),0,-Math.sin(frame.heading)),feature.theta*4);mesh.rotation.y+=frame.heading;mesh.userData.feature=feature;group.add(mesh)}return group}
function makePlayer(){const spec=VEHICLES[selectedVehicle]||VEHICLES.comet,group=new THREE.Group(),paint=new THREE.MeshStandardMaterial({color:spec.color,roughness:.24,metalness:.55}),dark=new THREE.MeshStandardMaterial({color:0x07161a,metalness:.86,roughness:.18}),glow=new THREE.MeshBasicMaterial({color:spec.accent});let body,base;if(selectedVehicle==='razor'){base=new THREE.Mesh(new THREE.BoxGeometry(1.65,.14,3.4),dark);body=new THREE.Mesh(new THREE.ConeGeometry(.72,3.1,5),paint);body.rotation.x=Math.PI/2;body.rotation.z=Math.PI;body.position.set(0,.52,.1)}else if(selectedVehicle==='trail'){base=new THREE.Mesh(new THREE.BoxGeometry(2.15,.25,2.75),dark);body=new THREE.Mesh(new THREE.BoxGeometry(1.25,.65,1.8),paint);body.position.set(0,.55,-.05);for(const x of[-1.08,1.08])for(const z of[-.82,.82]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,.28,12),dark);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.28,z);group.add(wheel)}}else if(selectedVehicle==='pulse'){base=new THREE.Mesh(new THREE.CapsuleGeometry(.34,2.5,4,10),paint);base.rotation.x=Math.PI/2;base.position.y=.24;body=new THREE.Mesh(new THREE.SphereGeometry(.64,16,10),dark);body.scale.set(1,.65,1.25);body.position.set(0,.62,-.05);for(const x of[-.92,.92]){const pod=new THREE.Mesh(new THREE.CapsuleGeometry(.18,1.55,4,8),glow);pod.rotation.x=Math.PI/2;pod.position.set(x,.22,.15);group.add(pod)}}else{base=new THREE.Mesh(new THREE.BoxGeometry(1.8,.16,2.7),dark);body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.2,5,10),paint);body.rotation.x=Math.PI/2;body.position.y=.75}base.position.y+=.15;group.add(base,body);const core=new THREE.Mesh(new THREE.SphereGeometry(.28,16,10),glow);core.position.set(0,.88,-.42);group.add(core);return group}
function makeDecor(){const group=new THREE.Group(),palette=[0xffd95a,0xff766d,0x6ce1aa,0x62b8ff,0xb47cff],trunkMat=new THREE.MeshStandardMaterial({color:0x754a37,roughness:.9}),archMat=new THREE.MeshStandardMaterial({color:0xffffff,emissive:0x74e5bd,emissiveIntensity:.25,roughness:.45});for(let i=10;i<samples.length;i+=18){const p=samples[i],right=new THREE.Vector3(Math.cos(p.heading),0,-Math.sin(p.heading));for(const side of[-1,1]){const root=new THREE.Group(),trunk=new THREE.Mesh(new THREE.CylinderGeometry(.25,.4,2.2,7),trunkMat),crown=new THREE.Mesh(new THREE.IcosahedronGeometry(1.5,1),new THREE.MeshStandardMaterial({color:palette[(i+side+6)%palette.length],roughness:.72}));trunk.position.y=1.1;crown.position.y=3;root.add(trunk,crown);root.position.set(p.x,p.y,p.z).addScaledVector(right,8+((i/18)%3)*2);root.scale.setScalar(.8+(i%5)*.08);group.add(root)}}for(let i=40;i<samples.length;i+=95){const p=samples[i],arch=new THREE.Group(),beam=new THREE.Mesh(new THREE.BoxGeometry(13,.45,.65),archMat),left=new THREE.Mesh(new THREE.BoxGeometry(.55,5,.55),archMat),right=new THREE.Mesh(new THREE.BoxGeometry(.55,5,.55),archMat);beam.position.y=5;left.position.set(-6,2.5,0);right.position.set(6,2.5,0);arch.add(beam,left,right);arch.position.set(p.x,p.y,p.z);arch.rotation.y=p.heading;group.add(arch)}const cloudMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:1});for(let i=0;i<26;i++){const cloud=new THREE.Group();for(let j=0;j<4;j++){const puff=new THREE.Mesh(new THREE.SphereGeometry(2+j*.35,10,8),cloudMat);puff.position.set(j*2.2,Math.sin(j)*.7,0);cloud.add(puff)}cloud.position.set((Math.random()-.5)*420,28+Math.random()*35,(Math.random()-.2)*620);cloud.scale.setScalar(.7+Math.random()*1.2);group.add(cloud)}return group}
function theme(name){const themes={reef:[0x73dff0,0x36aab0],alpine:[0x91d7ff,0x8bbfe0],'neon-city':[0x786fe8,0x5864ce],volcanic:[0xffaa78,0xc45b57],aurora:[0x72d8c7,0x55b9a3]},t=themes[name]||themes.reef;scene.background=new THREE.Color(t[0]);scene.fog.color.setHex(t[0]);track.material.color.setHex(t[1]);track.material.emissive=new THREE.Color(t[1]).multiplyScalar(.2);track.material.emissiveIntensity=.35}
function place(first=false){const f=at(state.distance),right=new THREE.Vector3(Math.cos(f.heading),0,-Math.sin(f.heading));player.position.set(f.x,f.y+.25,f.z).addScaledVector(right,state.lateral*4);player.rotation.y=f.heading;player.rotation.z=THREE.MathUtils.lerp(player.rotation.z,-state.lateral*.32,.16);const target=player.position.clone().add(new THREE.Vector3(0,1.2,0)),wanted=target.clone().add(new THREE.Vector3(-Math.sin(f.heading)*11,6,-Math.cos(f.heading)*11));camera.position.lerp(wanted,first?1:.09);camera.lookAt(target)}
function input(){let steer=(keys.has('ArrowRight')||keys.has('KeyD')||touch.right?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')||touch.left?1:0),lean=(keys.has('ArrowUp')||keys.has('KeyW')||touch.accelerate?1:0)-(keys.has('ArrowDown')||keys.has('KeyS')||touch.brake?1:0);const pad=navigator.getGamepads?.()[0];if(pad){if(Math.abs(pad.axes[0]||0)>.08)steer=pad.axes[0];if(Math.abs(pad.axes[1]||0)>.08)lean=-pad.axes[1]}return{steer,lean}}
function update(dt){if(phase==='countdown'){countdown+=dt;const n=3-Math.floor(countdown);$('countdown').querySelector('strong').textContent=n>0?n:'GO';if(countdown>=3.75)setPhase('race');return}if(phase!=='race')return;const spec=VEHICLES[selectedVehicle],controls=input(),penalty=state.penalties;controls.steer*=spec.steer;simulateStep(state,controls,map,{...DEFAULT_TUNING,baseSpeed:7,maxSpeed:spec.maxSpeed},dt);if(!controls.lean&&state.speed>8)state.speed=Math.max(8,state.speed-dt*2.2);if(Math.abs(state.lateral)>1.08){state.speed=Math.max(6,state.speed-dt*13/spec.stability);state.lateral*=1-dt*1.8*spec.stability;state.event='越界减速'}if(selectedVehicle==='pulse'&&Math.abs(controls.steer)>.55)state.driftCharge=Math.min(1.5,state.driftCharge+dt*.16);if(state.penalties>penalty)collisions++;maxSpeed=Math.max(maxSpeed,state.speed);place();features.children.forEach(mesh=>{if(mesh.userData.feature?.type==='item-box')mesh.rotation.y+=dt});if(state.distance>=totalLength(map))finish();hud()}
function hud(){$('speed').textContent=Math.round(state.speed*3.6);$('progress').textContent=`${Math.min(100,Math.floor(state.distance/totalLength(map)*100))}%`;$('time').textContent=format(state.elapsed+state.penalties);$('event').textContent=state.event||'保持平衡';$('charge-fill').style.width=`${Math.min(100,state.driftCharge/1.5*100)}%`;$('energy-value').textContent=`${state.energy}/10`;$('shield-indicator').hidden=state.shieldTimer<=0}const format=s=>`${Math.floor(s/60)}:${(s%60).toFixed(1).padStart(4,'0')}`;
function start(reuse=false){if(reuse)reset();else build((seed+2654435761)>>>0);place(true);countdown=0;$('countdown').querySelector('strong').textContent='3';setPhase('countdown')}function finish(){setPhase('results');$('result-title').textContent=collisions===0?'完美滑行':state.energy>=5?'核心车手':'完成比赛';$('result-time').textContent=format(state.elapsed+state.penalties);$('result-speed').textContent=Math.round(maxSpeed*3.6);$('result-energy').textContent=state.energy;$('result-hits').textContent=collisions}function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);renderer.render(scene,camera);requestAnimationFrame(frame)}
function selectVehicle(id){selectedVehicle=VEHICLES[id]?id:'comet';localStorage.setItem('core-luge.vehicle',selectedVehicle);document.querySelectorAll('[data-vehicle]').forEach(card=>{const active=card.dataset.vehicle===selectedVehicle;card.classList.toggle('selected',active);card.setAttribute('aria-checked',active)});$('selected-vehicle-name').textContent=VEHICLES[selectedVehicle].name;$('selected-vehicle-trait').textContent=VEHICLES[selectedVehicle].trait;if(player){dispose(player);player=makePlayer();world.add(player);place(true)}}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)});document.querySelectorAll('[data-vehicle]').forEach(card=>card.onclick=()=>selectVehicle(card.dataset.vehicle));$('garage-confirm').onclick=()=>setPhase('menu');$('change-vehicle').onclick=()=>setPhase('garage');$('start').onclick=()=>start();$('retry').onclick=()=>start(true);$('next').onclick=()=>start();$('pause').onclick=()=>setPhase('paused');$('resume').onclick=()=>setPhase('race');document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>setPhase('menu'));addEventListener('keydown',e=>{if(e.code.startsWith('Arrow'))e.preventDefault();keys.add(e.code);if(e.code==='Escape')setPhase(phase==='race'?'paused':phase==='paused'?'race':phase)});addEventListener('keyup',e=>keys.delete(e.code));document.querySelectorAll('[data-control]').forEach(b=>{const k=b.dataset.control,down=e=>{e.preventDefault();touch[k]=1;b.classList.add('active')},up=e=>{e.preventDefault();touch[k]=0;b.classList.remove('active')};b.onpointerdown=down;b.onpointerup=up;b.onpointercancel=up});selectVehicle(selectedVehicle);build();setPhase('garage');requestAnimationFrame(frame);
