import * as THREE from '../vendor/three.module.js';
import { generateMap } from './core/generator.js';
import { DEFAULT_TUNING, simulateStep } from './core/simulator.js';
import { totalLength } from './core/schema.js';

const $=id=>document.getElementById(id),canvas=$('game'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'}),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(61,innerWidth/innerHeight,.1,900),world=new THREE.Group(),keys=new Set(),touch={left:0,right:0,accelerate:0,brake:0};
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.55;scene.add(world,new THREE.HemisphereLight(0xc6ffff,0x102026,3.2));scene.fog=new THREE.FogExp2(0x071116,.0027);const sun=new THREE.DirectionalLight(0xffedce,4.5);sun.position.set(-8,14,-6);scene.add(sun);
const colors={boost:0x60ef9e,slow:0xf1b550,obstacle:0xff575f,jump:0x62b7ff,'slow-wall':0xd57bcf,energy:0xffe75f,'item-box':0x55ddf2,oil:0x705588,'moving-gate':0xff8568};
let map,state,samples,phase='menu',seed=4517,countdown=0,last=performance.now(),maxSpeed=0,collisions=0,track,features,player,decor;
function setPhase(next){phase=next;for(const id of['menu','countdown','paused','results'])$(id).hidden=next!==id;const racing=['countdown','race'].includes(next);$('race-hud').hidden=!racing;$('energy').hidden=!racing;$('pause').hidden=next!=='race';$('touch-controls').hidden=next!=='race'}
function dispose(group){if(!group)return;group.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose?.()});group.removeFromParent()}
function reset(){state={speed:4,lateral:0,distance:0,elapsed:0,penalties:0,hit:new Set(),energy:0,combo:0,driftCharge:0,boostTimer:0,shieldTimer:0,event:'后仰加速'};maxSpeed=collisions=0}
function build(nextSeed=seed){seed=nextSeed>>>0;map=generateMap({seed,duration:105,difficulty:Number($('difficulty').value),complexity:.72,shape:'mixed',environment:['reef','alpine','neon-city','volcanic','aurora'][seed%5]});reset();[track,features,player,decor].forEach(dispose);samples=sampleCourse(map);track=makeTrack();features=makeFeatures();player=makePlayer();decor=makeDecor();world.add(track,features,player,decor);theme(map.environment);place(true)}
function sampleCourse(course){const out=[];let x=0,y=0,z=0,heading=0,distance=0;for(const segment of course.segments){const steps=Math.max(4,Math.ceil(segment.len/4));for(let i=0;i<steps;i++){heading+=(segment.yaw||0)*Math.PI/180/steps;const slope=(segment.drop||0)*Math.PI/180;x+=Math.sin(heading)*4;z+=Math.cos(heading)*4;y-=Math.sin(slope)*4;out.push({x,y,z,heading,distance,segment});distance+=4}}return out}
function at(distance){const i=Math.max(0,Math.min(samples.length-2,Math.floor(distance/4))),a=samples[i],b=samples[i+1],t=(distance-a.distance)/Math.max(1,b.distance-a.distance);return{x:THREE.MathUtils.lerp(a.x,b.x,t),y:THREE.MathUtils.lerp(a.y,b.y,t),z:THREE.MathUtils.lerp(a.z,b.z,t),heading:THREE.MathUtils.lerp(a.heading,b.heading,t),segment:a.segment}}
function makeTrack(){const geo=new THREE.BufferGeometry(),v=[],c=[],ind=[],width=11;for(let i=0;i<samples.length;i++){const p=samples[i],rx=Math.cos(p.heading),rz=-Math.sin(p.heading);for(let lane=0;lane<=12;lane++){const u=lane/12,across=(u-.5)*width,bank=Math.sin(u*Math.PI)*1.15,edge=Math.min(u,1-u),glow=edge<.09?1:.2;v.push(p.x+rx*across,p.y-bank,p.z+rz*across);c.push(.12+glow*.12,.25+glow*.52,.28+glow*.55);if(i<samples.length-1&&lane<12){const a=i*13+lane,b=a+13;ind.push(a,b,a+1,a+1,b,b+1)}}}geo.setAttribute('position',new THREE.Float32BufferAttribute(v,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(c,3));geo.setIndex(ind);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.63,metalness:.25,side:THREE.DoubleSide}));const lineMat=new THREE.LineBasicMaterial({color:0x78f9e4});for(const side of[-1,1]){const points=samples.filter((_,i)=>i%2===0).map(p=>new THREE.Vector3(p.x+Math.cos(p.heading)*width*.5*side,p.y+.08,p.z-Math.sin(p.heading)*width*.5*side));mesh.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),lineMat))}return mesh}
function distanceOf(feature){let d=0;for(const segment of map.segments){if(segment.id===feature.segmentId)return d+feature.offset;d+=segment.len}return 0}
function makeFeatures(){const group=new THREE.Group();for(const feature of map.features){const frame=at(distanceOf(feature)),mat=new THREE.MeshStandardMaterial({color:colors[feature.type]||0xffffff,emissive:colors[feature.type]||0xffffff,emissiveIntensity:.7,roughness:.3});let mesh;if(feature.type==='energy'){mesh=new THREE.Mesh(new THREE.TorusGeometry(.7,.16,10,24),mat);mesh.position.y=1.2}else if(feature.type==='item-box'){mesh=new THREE.Mesh(new THREE.BoxGeometry(1.25,1.25,1.25),mat);mesh.rotation.y=Math.PI/4;mesh.position.y=1}else if(['obstacle','moving-gate'].includes(feature.type)){mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(1.6,feature.width*4),1.5,1),mat);mesh.position.y=.75}else{mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(1.4,feature.width*5),.12,Math.max(2,feature.length)),mat);mesh.position.y=.08}mesh.position.add(new THREE.Vector3(frame.x,frame.y,frame.z)).addScaledVector(new THREE.Vector3(Math.cos(frame.heading),0,-Math.sin(frame.heading)),feature.theta*4);mesh.rotation.y+=frame.heading;mesh.userData.feature=feature;group.add(mesh)}return group}
function makePlayer(){const group=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.2,5,10),new THREE.MeshStandardMaterial({color:0x65e29f,roughness:.25,metalness:.4}));body.rotation.x=Math.PI/2;body.position.y=.75;group.add(body);const runner=new THREE.Mesh(new THREE.BoxGeometry(1.8,.16,2.7),new THREE.MeshStandardMaterial({color:0x07161a,metalness:.85,roughness:.2}));runner.position.y=.15;group.add(runner);const core=new THREE.Mesh(new THREE.SphereGeometry(.3,16,10),new THREE.MeshBasicMaterial({color:0xeafff3}));core.position.set(0,.92,-.42);group.add(core);return group}
function makeDecor(){const group=new THREE.Group(),geo=new THREE.IcosahedronGeometry(.12,0),mat=new THREE.MeshBasicMaterial({color:0x9cf7e6});for(let i=0;i<260;i++){const star=new THREE.Mesh(geo,mat);star.position.set((Math.random()-.5)*430,Math.random()*100-35,(Math.random()-.15)*650);star.scale.setScalar(.5+Math.random()*2);group.add(star)}return group}
function theme(name){const themes={reef:[0x06181d,0x0c3139],alpine:[0x07151d,0x173746],'neon-city':[0x090718,0x241650],volcanic:[0x180906,0x46170e],aurora:[0x06141b,0x124546]},t=themes[name]||themes.reef;scene.background=new THREE.Color(t[0]);scene.fog.color.setHex(t[0]);track.material.color.setHex(t[1])}
function place(first=false){const f=at(state.distance),right=new THREE.Vector3(Math.cos(f.heading),0,-Math.sin(f.heading));player.position.set(f.x,f.y+.25,f.z).addScaledVector(right,state.lateral*4);player.rotation.y=f.heading;player.rotation.z=THREE.MathUtils.lerp(player.rotation.z,-state.lateral*.32,.16);const target=player.position.clone().add(new THREE.Vector3(0,1.2,0)),wanted=target.clone().add(new THREE.Vector3(-Math.sin(f.heading)*11,6,-Math.cos(f.heading)*11));camera.position.lerp(wanted,first?1:.09);camera.lookAt(target)}
function input(){let steer=(keys.has('ArrowRight')||keys.has('KeyD')||touch.right?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')||touch.left?1:0),lean=(keys.has('ArrowUp')||keys.has('KeyW')||touch.accelerate?1:0)-(keys.has('ArrowDown')||keys.has('KeyS')||touch.brake?1:0);const pad=navigator.getGamepads?.()[0];if(pad){if(Math.abs(pad.axes[0]||0)>.08)steer=pad.axes[0];if(Math.abs(pad.axes[1]||0)>.08)lean=-pad.axes[1]}return{steer,lean}}
function update(dt){if(phase==='countdown'){countdown+=dt;const n=3-Math.floor(countdown);$('countdown').querySelector('strong').textContent=n>0?n:'GO';if(countdown>=3.75)setPhase('race');return}if(phase!=='race')return;const controls=input(),penalty=state.penalties;simulateStep(state,controls,map,{...DEFAULT_TUNING,baseSpeed:7,maxSpeed:42},dt);if(!controls.lean&&state.speed>8)state.speed=Math.max(8,state.speed-dt*2.2);if(Math.abs(state.lateral)>1.08){state.speed=Math.max(6,state.speed-dt*13);state.lateral*=1-dt*1.8;state.event='越界减速'}if(state.penalties>penalty)collisions++;maxSpeed=Math.max(maxSpeed,state.speed);place();features.children.forEach(mesh=>{if(mesh.userData.feature?.type==='item-box')mesh.rotation.y+=dt});if(state.distance>=totalLength(map))finish();hud()}
function hud(){$('speed').textContent=Math.round(state.speed*3.6);$('progress').textContent=`${Math.min(100,Math.floor(state.distance/totalLength(map)*100))}%`;$('time').textContent=format(state.elapsed+state.penalties);$('event').textContent=state.event||'保持平衡';$('charge-fill').style.width=`${Math.min(100,state.driftCharge/1.5*100)}%`;$('energy-value').textContent=`${state.energy}/10`;$('shield-indicator').hidden=state.shieldTimer<=0}const format=s=>`${Math.floor(s/60)}:${(s%60).toFixed(1).padStart(4,'0')}`;
function start(reuse=false){if(reuse)reset();else build((seed+2654435761)>>>0);place(true);countdown=0;$('countdown').querySelector('strong').textContent='3';setPhase('countdown')}function finish(){setPhase('results');$('result-title').textContent=collisions===0?'完美滑行':state.energy>=5?'核心车手':'完成比赛';$('result-time').textContent=format(state.elapsed+state.penalties);$('result-speed').textContent=Math.round(maxSpeed*3.6);$('result-energy').textContent=state.energy;$('result-hits').textContent=collisions}function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);renderer.render(scene,camera);requestAnimationFrame(frame)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)});$('start').onclick=()=>start();$('retry').onclick=()=>start(true);$('next').onclick=()=>start();$('pause').onclick=()=>setPhase('paused');$('resume').onclick=()=>setPhase('race');document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>setPhase('menu'));addEventListener('keydown',e=>{if(e.code.startsWith('Arrow'))e.preventDefault();keys.add(e.code);if(e.code==='Escape')setPhase(phase==='race'?'paused':phase==='paused'?'race':phase)});addEventListener('keyup',e=>keys.delete(e.code));document.querySelectorAll('[data-control]').forEach(b=>{const k=b.dataset.control,down=e=>{e.preventDefault();touch[k]=1;b.classList.add('active')},up=e=>{e.preventDefault();touch[k]=0;b.classList.remove('active')};b.onpointerdown=down;b.onpointerup=up;b.onpointercancel=up});build();setPhase('menu');requestAnimationFrame(frame);
