import { generateMap } from './core/generator.js';
import { DEFAULT_TUNING, simulateStep } from './core/simulator.js';
import { totalLength } from './core/schema.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),keys=new Set(),touch={left:0,right:0,accelerate:0,brake:0};
const colors={boost:'#5ff0a0','turbo-bottle':'#ffd85a',slow:'#f2b955',obstacle:'#ff6363',jump:'#6dbeff','slow-wall':'#d783cf',energy:'#ffe65c','item-box':'#57e4f5',oil:'#775b8e','moving-gate':'#ff8a69'};
const env={reef:['#05171c','#0d3f48','#41c8bc'],alpine:['#07131d','#244657','#d7f3f4'],'neon-city':['#09071a','#30205e','#ff5da8'],volcanic:['#180b08','#4b1d13','#ff7247'],aurora:['#071420','#174b50','#73f4bd']};
let map,state,phase='menu',last=performance.now(),seed=4517,countdown=0,flash=0,shake=0,maxSpeed=0,collisions=0,lastPenalty=0;
function resize(){const r=Math.min(devicePixelRatio,2);canvas.width=innerWidth*r;canvas.height=innerHeight*r;canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(r,0,0,r,0,0)}addEventListener('resize',resize);resize();
function setPhase(next){phase=next;for(const id of ['menu','countdown','paused','results'])$(id).hidden=next!==id;const racing=['countdown','race'].includes(next);$('race-hud').hidden=!racing;$('energy').hidden=!racing;$('pause').hidden=next!=='race';$('touch-controls').hidden=next!=='race'}
function reset(){state={speed:10,lateral:0,distance:0,elapsed:0,penalties:0,hit:new Set(),energy:0,combo:0,driftCharge:0,boostTimer:0,shieldTimer:0,jumpTimer:0,event:''};maxSpeed=collisions=lastPenalty=flash=shake=0}
function build(nextSeed=seed){seed=nextSeed>>>0;map=generateMap({seed,duration:105,difficulty:Number($('difficulty').value),complexity:.7,shape:'mixed',environment:Object.keys(env)[seed%5]});reset()}
function start(reuse=false){if(reuse)reset();else build((seed+2654435761)>>>0);countdown=0;$('countdown').querySelector('strong').textContent='3';setPhase('countdown')}
function input(){let steer=(keys.has('ArrowRight')||keys.has('KeyD')||touch.right?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')||touch.left?1:0),lean=(keys.has('ArrowUp')||keys.has('KeyW')||touch.accelerate?1:0)-(keys.has('ArrowDown')||keys.has('KeyS')||touch.brake?1:0);const pad=navigator.getGamepads?.()[0];if(pad){if(Math.abs(pad.axes[0]||0)>.08)steer=pad.axes[0];if(Math.abs(pad.axes[1]||0)>.08)lean=-pad.axes[1]}return{steer,lean}}
function update(dt){flash=Math.max(0,flash-dt*1.8);shake=Math.max(0,shake-dt*7);if(phase==='countdown'){countdown+=dt;const n=3-Math.floor(countdown);$('countdown').querySelector('strong').textContent=n>0?n:'GO';if(countdown>=3.75)setPhase('race');return}if(phase!=='race')return;const event=state.event;simulateStep(state,input(),map,DEFAULT_TUNING,dt);maxSpeed=Math.max(maxSpeed,state.speed);if(state.penalties>lastPenalty){collisions++;lastPenalty=state.penalties;shake=1;flash=.8}if(state.event!==event&&state.event)flash=Math.max(flash,.35);if(state.distance>=totalLength(map))finish();hud()}
function finish(){setPhase('results');$('result-title').textContent=collisions===0?'完美滑行':state.energy>=5?'核心车手':'完成比赛';$('result-time').textContent=time(state.elapsed+state.penalties);$('result-speed').textContent=Math.round(maxSpeed*3.6);$('result-energy').textContent=state.energy;$('result-hits').textContent=collisions}
function hud(){$('speed').textContent=Math.round(state.speed*3.6);$('progress').textContent=`${Math.min(100,Math.floor(state.distance/totalLength(map)*100))}%`;$('time').textContent=time(state.elapsed+state.penalties);$('event').textContent=state.event||'保持平衡';$('charge-fill').style.width=`${Math.min(100,state.driftCharge/1.5*100)}%`;$('energy-value').textContent=`${state.energy}/10`;$('shield-indicator').hidden=state.shieldTimer<=0}const time=s=>`${Math.floor(s/60)}:${(s%60).toFixed(1).padStart(4,'0')}`;
function segmentAt(d){let start=0;for(const segment of map.segments){if(d<start+segment.len)return segment;start+=segment.len}return map.segments.at(-1)}function featureDistance(feature){let d=0;for(const segment of map.segments){if(segment.id===feature.segmentId)return d+feature.offset;d+=segment.len}return Infinity}
function draw(){const w=innerWidth,h=innerHeight,p=env[map.environment],g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,p[0]);g.addColorStop(.6,p[1]);g.addColorStop(1,'#061013');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);background(w,h,p);ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake*12,(Math.random()-.5)*shake*8);const horizon=h*.34,strips=[];let bend=0;for(let i=65;i>=0;i--){const t=i/65,ahead=(1-t)**2*520,segment=segmentAt(Math.min(totalLength(map)-1,state.distance+ahead));bend+=(segment.yaw||0)/Math.max(100,segment.len)*(1.15-t)*7;strips.push({t,ahead,y:horizon+(1-t)**2*(h-horizon+70),half:18+(1-t)**2*w*.46,center:w/2+bend*w*.035-state.lateral*(1-t)*w*.19})}ctx.beginPath();strips.forEach((s,i)=>i?ctx.lineTo(s.center-s.half,s.y):ctx.moveTo(s.center-s.half,s.y));for(let i=strips.length-1;i>=0;i--)ctx.lineTo(strips[i].center+strips[i].half,strips[i].y);ctx.closePath();ctx.fillStyle='#183138';ctx.fill();ctx.strokeStyle=p[2];ctx.lineWidth=3;ctx.stroke();for(let i=0;i<strips.length;i+=4){const s=strips[i];ctx.strokeStyle=`rgba(130,220,210,${.08+(1-s.t)*.18})`;ctx.beginPath();ctx.moveTo(s.center-s.half,s.y);ctx.lineTo(s.center+s.half,s.y);ctx.stroke()}features(strips);const x=w/2+state.lateral*w*.16,y=h*.79;ctx.fillStyle=state.boostTimer>0?'#ffe25c':'#66e2a1';ctx.fillRect(x-25,y,50,72);ctx.fillStyle='#e8fff3';ctx.fillRect(x-7,y+9,14,27);ctx.fillStyle='#122429';ctx.fillRect(x-31,y+62,62,9);ctx.restore();if(flash){ctx.fillStyle=`rgba(${collisions?'255,75,65':'255,235,100'},${flash*.18})`;ctx.fillRect(0,0,w,h)}}
function features(strips){for(const {feature,ahead} of map.features.map(feature=>({feature,ahead:featureDistance(feature)-state.distance})).filter(x=>x.ahead>2&&x.ahead<520&&!state.hit.has(x.feature.id)).sort((a,b)=>b.ahead-a.ahead)){const n=1-Math.sqrt(ahead/520),s=strips[Math.max(0,Math.min(strips.length-1,Math.round((1-n)*strips.length)))],x=s.center+feature.theta*s.half*.75,size=5+n*n*55;ctx.fillStyle=colors[feature.type]||'#fff';if(feature.type==='energy'){ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=Math.max(2,size*.18);ctx.beginPath();ctx.arc(x,s.y-size*.55,size*.38,0,Math.PI*2);ctx.stroke()}else if(feature.type==='turbo-bottle'){ctx.beginPath();ctx.roundRect(x-size*.24,s.y-size,size*.48,size*.82,size*.18);ctx.fill();ctx.fillStyle='#fff4bf';ctx.fillRect(x-size*.13,s.y-size*1.12,size*.26,size*.18)}else if(feature.type==='item-box'){ctx.fillRect(x-size*.4,s.y-size,size*.8,size*.8);ctx.fillStyle='#092028';ctx.font=`bold ${size*.55}px sans-serif`;ctx.textAlign='center';ctx.fillText('?',x,s.y-size*.35)}else ctx.fillRect(x-size*.5,s.y-size*.45,size,Math.max(4,size*.45))}}
function background(w,h,p){ctx.fillStyle='rgba(255,255,255,.05)';for(let i=0;i<24;i++){ctx.beginPath();ctx.arc((i*193+seed)%w,(i*83+seed)%(h*.5),1+i%3,0,Math.PI*2);ctx.fill()}ctx.fillStyle=p[1];for(let i=0;i<8;i++){const x=i*w/7;ctx.beginPath();ctx.moveTo(x-w*.16,h*.44);ctx.lineTo(x,h*(.15+i%3*.07));ctx.lineTo(x+w*.18,h*.44);ctx.fill()}}
function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(frame)}
$('start').onclick=()=>start();$('retry').onclick=()=>start(true);$('next').onclick=()=>start();$('pause').onclick=()=>setPhase('paused');$('resume').onclick=()=>setPhase('race');document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>setPhase('menu'));addEventListener('keydown',e=>{if(e.code.startsWith('Arrow'))e.preventDefault();keys.add(e.code);if(e.code==='Escape')setPhase(phase==='race'?'paused':phase==='paused'?'race':phase)});addEventListener('keyup',e=>keys.delete(e.code));document.querySelectorAll('[data-control]').forEach(b=>{const k=b.dataset.control,down=e=>{e.preventDefault();touch[k]=1;b.classList.add('active')},up=e=>{e.preventDefault();touch[k]=0;b.classList.remove('active')};b.onpointerdown=down;b.onpointerup=up;b.onpointercancel=up});build();setPhase('menu');requestAnimationFrame(frame);
